### ISSUE TITLE
Not found in PubMed, although DOI (.ORG/10.1016/J.BBAGRM.2015.08.009) was detected 

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/pubmex#1]
magnus@maximus:~/Desktop/pdfs$ pubmex.py -a -r -f 1-s2.0-S1874939915001868-main.pdf 
ERROR:      Not found in PubMed, although DOI (.ORG/10.1016/J.BBAGRM.2015.08.009) was detected in the pdf!
Traceback (most recent call last):
  File "/home/magnus/bin/pubmex.py", line 472, in <module>
    main()
  File "/home/magnus/bin/pubmex.py", line 451, in main
    title = get_title_auto_from_text(text, OPTIONS.debug, False, OPTIONS.keywords)
  File "/home/magnus/bin/pubmex.py", line 239, in get_title_auto_from_text
    return get_title_via_doi(doi, debug, reference, customed_title)
  File "/home/magnus/bin/pubmex.py", line 359, in get_title_via_doi
    pmid = get_pmid_via_doi_net(doi)
  File "/home/magnus/bin/pubmex.py", line 333, in get_pmid_via_doi_net
    return get_value('citation_pmid', content)
TypeError: get_value() takes exactly 3 arguments (2 given)

**Comment by mmagnus** [comment]
magnus@maximus:~/Desktop/pdfs$ pubmex.py -d -r -a -f 1-s2.0-S1874939915001868-main.pdf 
debug:.............. on
options: ........... {'rename': True, 'filename': '1-s2.0-S1874939915001868-main.pdf', 'debug': True, 'PMID_or_DOI': None, 'keywords': None, 'automatic': True}
arguments: ......... []
filename: .......... 1-s2.0-S1874939915001868-main.pdf
generate ./temp.....[OK]
temp is going to be opened
doi_line: .......... HTTP://DX.DOI.ORG/10.1016/J.BBAGRM.2015.08.009
doi is found: ...... .ORG/10.1016/J.BBAGRM.2015.08.009
doi: ............... .ORG/10.1016/J.BBAGRM.2015.08.009
IdList.............. ['25319526', '25077353', '25077352']
pmid: .............. False
ERROR:      Not found in PubMed, although DOI (.ORG/10.1016/J.BBAGRM.2015.08.009) was detected in the pdf!
Traceback (most recent call last):
  File "/home/magnus/bin/pubmex.py", line 472, in <module>
    main()
  File "/home/magnus/bin/pubmex.py", line 451, in main
    title = get_title_auto_from_text(text, OPTIONS.debug, False, OPTIONS.keywords)
  File "/home/magnus/bin/pubmex.py", line 239, in get_title_auto_from_text
    return get_title_via_doi(doi, debug, reference, customed_title)
  File "/home/magnus/bin/pubmex.py", line 359, in get_title_via_doi
    pmid = get_pmid_via_doi_net(doi)
  File "/home/magnus/bin/pubmex.py", line 333, in get_pmid_via_doi_net
    return get_value('citation_pmid', content)
TypeError: get_value() takes exactly 3 arguments (2 given)

**Comment by mmagnus** [comment]
```
(py37) [mx] Desktop$ pubmex -d -a -f blythe2016.pdf
filename: .......... blythe2016.pdf
doi: ............... blythe2016
IdList.............. []
pmid: .............. False
ERROR: 		Not found in PubMed, although DOI (blythe2016) was detected in the pdf!
doi: ............... 10.1016/j.bbagrm.2015.08.009
IdList.............. ['26325022']
pmid: .............. 26325022
summary_dict........ {'Item': [], 'Id': '26325022', 'PubDate': '2016 Jan', 'EPubDate': '2015 Aug 29', 'Source': 'Biochim Biophys Acta', 'AuthorList': ['Blythe AJ', 'Fox AH', 'Bond CS'], 'LastAuthor': 'Bond CS', 'Title': 'The ins and outs of lncRNA structure: How, why and what comes next?', 'Volume': '1859', 'Issue': '1', 'Pages': '46-58', 'LangList': ['English'], 'NlmUniqueID': '0217513', 'ISSN': '0006-3002', 'ESSN': '1878-2434', 'PubTypeList': ['Journal Article', 'Review'], 'RecordStatus': 'PubMed - indexed for MEDLINE', 'PubStatus': 'ppublish+epublish', 'ArticleIds': {'medline': [], 'pubmed': ['26325022'], 'pii': 'S1874-9399(15)00186-8', 'doi': '10.1016/j.bbagrm.2015.08.009', 'rid': '26325022', 'eid': '26325022'}, 'DOI': '10.1016/j.bbagrm.2015.08.009', 'History': {'medline': ['2016/05/27 06:00'], 'pubmed': ['2015/09/02 06:00'], 'received': '2015/05/15 00:00', 'revised': '2015/08/07 00:00', 'accepted': '2015/08/27 00:00', 'entrez': '2015/09/02 06:00'}, 'References': [], 'HasAbstract': IntegerElement(1, attributes={}), 'PmcRefCount': IntegerElement(35, attributes={}), 'FullJournalName': 'Biochimica et biophysica acta', 'ELocationID': 'doi: 10.1016/j.bbagrm.2015.08.009', 'SO': '2016 Jan;1859(1):46-58'}
the title is ...  Blythe.Bond.The.ins.outs.lncRNA.structure.How.why.what.comes.next.BBA.2016.pdf
False
CAUTION! THE FILE WAS NOT RENAME, ADD -r OPTION TO RENAME THE FILE. IF YOU USE -r THE PUBMEX WILL DO
 mv blythe2016.pdf --> ./Blythe.Bond.The.ins.outs.lncRNA.structure.How.why.what.comes.next.BBA.2016.pdf
```

works right now.
